sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
- 2.2.5
- 2.1.10
- 2.0.0
- jruby-1.7.26
- jruby-9.1.5.0
matrix:
  allow_failures:
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.5.0
before_install:
- rvm get head
- rvm reload
- rvm use $TRAVIS_RUBY_VERSION --install --fuzzy
- rvm @global do gem install bundler
- ruby --version
- bundle --version
- gem --version
