sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
- 2.2.5
- 2.1.10
- 2.0.0
- 1.9.3
- jruby
- rbx
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx
before_install:
- rvm get head
- rvm reload
- rvm use --install $TRAVIS_RUBY_VERSION
