sudo: false
dist: trusty
cache: bundler
language: ruby
rvm:
- '2.4.1'
- '2.3.4'
- '2.2.7'
- '2.1.10'
- jruby-1.7.26
- jruby-9.1.8.0
matrix:
  allow_failures:
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.8.0
  fast_finish: true
before_install:
- gem update --system
- gem install bundler
