sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
- 2.2.5
- 2.1.10
- 2.0.0
- 1.9.3
- jruby
- rbx-2
- rbx-3
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
    - rvm: rbx-3
before_install:
- rvm get head
- rvm reload
- rvm use $TRAVIS_RUBY_VERSION --install --fuzzy
- gem install bundler
